### ISSUE TITLE
Failure at Restart lxcbr0 interface

### ISSUE THREAD

**Issue by ewjoachim** [toopy/ansible-role-lxc-dev#21]
The error is :
```
fatal: [spartacus3]: FAILED! => {"changed": true, "cmd": ["ifconfig", "lxcbr0", "up"], "delta": "0:00:00.005479", "end": "2017-02-07 10:38:54.884697", "failed": true, "rc": 255, "start": "2017-02-07 10:38:54.879218", "stderr": "lxcbr0: ERROR while getting interface flags: Aucun périphérique de ce type", "stdout": "", "stdout_lines": [], "warnings": []}
```

```yaml
- name: Restart lxcbr0 interface
  command: ifconfig lxcbr0 up
  when: lxc_dev_enable_bridge
```

https://github.com/toopy/ansible-role-lxc-dev/blob/09bee21012d137a8bb717019d6d5b68225761048/tasks/main.yml#L114-L116

@bersace suspects it's missing a `ifup lxcbr0` ?
